# https://rust-lang.github.io/mdBook/format/configuration/general.html#build-options
[build]
build-dir = "website"
extra-watch-dirs = ["docs/skeleton"]
[book]
authors = ["Lachezar Lechev"]
language = "en"
multilingual = false
src = "docs"
title = "Nanosatellite embedded workshop"

[output.html]
theme = "./docs/theme"
input-404 = "Not_found.md"

git-repository-url = "https://github.com/AeroRust/nanosat-workshop"

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter
