[workspace]

members = ["onboard-computer", "power-system"]

[workspace.dependencies]
# requires `esp32s2-hal/embassy-time-timg0`!
# esp-wifi = { git = "https://github.com/esp-rs/esp-wifi", rev = "74e9f18", features = ["esp32c3", "wifi", "embedded-svc", "embassy-net"], optional = true }
esp-wifi = { git = "https://github.com/esp-rs/esp-wifi", rev = "e5a1cf8", version = "0.1", features = [
    "esp32c3",
    "wifi",
    "embassy-net",
    "embedded-svc",
] }

# debugging
esp-backtrace = { version = "0.7", features = [
    "esp32c3",
    "panic-handler",
    "print-uart",
] }
esp-println = { version = "0.5", features = ["esp32c3"] }

# Allocator
# esp-alloc = { version = "0.3.0", features = ["oom-handler"] }

# Embassy
embassy-executor = { version = "0.2", features = [
    "nightly",
    "integrated-timers",
    "executor-thread",
] }
embassy-sync = { version = "0.2.0", features = ["nightly", "defmt"] }
embassy-futures = { version = "0.1.0", features = ["defmt"] }
embassy-net = { git = "https://github.com/embassy-rs/embassy", rev = "fb27594", features = [
    "nightly",
    "defmt",
    "udp",
    "dhcpv4",
    "medium-ethernet",
] }
embassy-net-driver = { git = "https://github.com/embassy-rs/embassy", rev = "fb27594" }
# todo: update to 0.1.1 with embedded-hal-nb alpha 2
embassy-time = { version = "0.1.1", features = ["nightly"] }

# Keep the same as in esp-wifi
embedded-svc = { version = "0.24", default-features = false, features = [
    "defmt",
] }

embedded-hal = { version = "0.2.7", features = ["unproven"] }
# todo: update to embedded-hal alpha 10
embedded-hal-1 = { version = "=1.0.0-alpha.10", package = "embedded-hal" }
# todo: update to alpha.1 with embedded-hal alpha 10
embedded-hal-async = { version = "0.2.0-alpha.1" }
# todo: update to alpha 2 with embedded hal alpha 10
embedded-hal-nb = { version = "=1.0.0-alpha.2" }
embedded-can = { version = "0.4.1" }

defmt = { version = "0.3" }
defmt-rtt = "0.4.0"

# required for running tests
critical-section = { version = "1.1" }

nmea = { version = "0.5.0", default-features = false }

static_cell = "1.0"
# once_cell = { version = "1.0", default-features = false, features = ["critical-section"] }
fugit = { version = "0.3", features = ["defmt"] }

nb = { version = "1.1.0", features = ["defmt-0-3"] }
heapless = { version = "0.7.16", features = ["defmt"] }

[patch.crates-io]
esp-hal-common = { git = "https://github.com/esp-rs/esp-hal", rev = "5c5d7f9" }
esp32c3-hal = { git = "https://github.com/esp-rs/esp-hal", rev = "5c5d7f9" }
