[workspace]

members = [
    #"onboard-computer",
    "power-system"
]

[workspace.dependencies]
# Base crates
# hal = { version = "0.7", package = "esp32c3-hal", features = ["rt", "embassy", "eh1", "vectored", "async", "embassy-time-systick"], git = "https://github.com/esp-rs/esp-hal.git", rev = "2eeb3db" }
hal = { package = "esp32c3-hal", version = "0.8", features = ["rt", "embassy", "eh1", "vectored", "async", ] }
# esp32c3 = { version = "0.14", features = ["critical-section"]}
# hal = { version = "0.7", package = "esp32c3-hal", features = ["rt", "embassy", "eh1", "vectored", "async", "embassy-time-timg0"], git = "https://github.com/esp-rs/esp-hal.git", rev = "2eeb3db" }
# requires `esp32s2-hal/embassy-time-timg0`!
# esp-wifi = { git = "https://github.com/esp-rs/esp-wifi", rev = "74e9f18", features = ["esp32c3", "wifi", "embedded-svc", "embassy-net"], optional = true }
esp-wifi = { path = "../esp-wifi/esp-wifi", features = ["esp32c3", "wifi", "embedded-svc", "embassy-net"] }

# debugging
esp-backtrace = { version = "0.7", features = ["esp32c3", "panic-handler", "print-uart"] }
esp-println = { version = "0.5", features = ["esp32c3"] }

# Allocator
# esp-alloc = { version = "0.3.0", features = ["oom-handler"] }

# Embassy
# embassy latest main ref: f9c0c53
# esp32c3-hal rev: cd9a65b
# esp-wifi embassy-executor rev: cd9a65b
# executor with new features: e2516bb
# embassy-executor  = { git = "https://github.com/embassy-rs/embassy", rev = "26474ce", features = ["nightly", "integrated-timers"] }
embassy-executor  = { git = "https://github.com/embassy-rs/embassy", rev = "e2516bb", features = ["nightly", "integrated-timers", "executor-thread"] }
embassy-sync       = { version = "0.2.0", features = ["nightly", "defmt"]}
embassy-futures = { version = "0.1.0",  features = ["defmt"] }
embassy-net = { git = "https://github.com/embassy-rs/embassy", rev = "26474ce", features = ["nightly", "defmt", "udp", "dhcpv4", "medium-ethernet"] }
embassy-net-driver = { git = "https://github.com/embassy-rs/embassy", rev = "26474ce" }
embassy-time       = { version = "0.1.0", features = ["nightly"], git = "https://github.com/embassy-rs/embassy", rev = "26474ce" }

# Keep the same as in esp-wifi
embedded-svc = { version = "0.24", default-features = false, features = ["defmt"] }

embedded-hal       = { version = "0.2.7", features = ["unproven"] }
embedded-hal-1     = { version = "=1.0.0-alpha.9", package = "embedded-hal" }
embedded-hal-async = { version = "0.1.0-alpha.3" }
embedded-hal-nb    = { version = "=1.0.0-alpha.1" }
embedded-can       = { version = "0.4.1" }

defmt = { version = "0.3" }
defmt-rtt = "0.4.0"

# required for running tests
# critical-section = { version = "1.1" }

static_cell = "1.0"
once_cell = { version = "1.0" }
# once_cell = { version = "1.0", default-features = false }
fugit = { version = "0.3", features = ["defmt"] }

nb = { version = "1.1.0", features = ["defmt-0-3"] }
heapless = { version = "0.7.16", features = ["defmt"] }