[env]
DEFMT_LOG = "info"

# RP Pico
[target.thumbv6m-none-eabi]

# [target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040"
# runner = "probe-rs run --chip RP235x"
# runner = "elf2uf2-rs -d"

# RP Pico 2
[target.thumbv8m.main-none-eabihf]
# runner = "picotool load -u -v -x -t elf"
runner = "probe-rs run --chip RP235x"

rustdocflags = [
    # "--enable-index-page",
    # "-Z", "unstable-options",
    # "--cfg", "docsrs",
]

[alias]
# run-firmware = "run --target thumbv6m-none-eabi --no-default-features -F firmware"
run-pico-w = "run --target thumbv6m-none-eabi --release --no-default-features -F rp2040 -F defmt"
run-demo-sd = "run --target thumbv6m-none-eabi --release --no-default-features -F demo-sd"

