[package]
name = "onboard-computer"
version = "0.1.0"
authors = ["Lechev.space <dev@lechev.space>, Lachezar Lechev <elpiel93@gmail.com>"]
license = "MIT OR Apache-2.0"

edition = "2021"
publish = false

default-run = "onboard-computer"

[features]
# default = ["riscv", "run-gnss", "run-pressure-and-temperature"]
# default = ["riscv"]

# esp32-c3 = ["riscv", "dep:shtcx", "dep:icm42670", "dep:log", "dep:esp-backtrace",
esp32-c3 = [
    "dep:esp32c3",
    "esp32c3/riscv",
    "dep:esp-backtrace",
    "dep:esp-println",
    "dep:hal",
]
# TODO: fix me!
pico-w = ["cortex-m", "dep:pico-w", "rp2040", "defmt"]

demo-pressure = ["cortex-m", "rp2040", "defmt", "dep:pico-w", "pico-w/demo-pressure"]

demo-obc-wifi = ["cortex-m", "rp2040", "defmt", "dep:pico-w", "pico-w/demo-obc-wifi", "pico-w/wifi"]
demo-obc-ap = ["cortex-m", "rp2040", "defmt", "dep:pico-w", "pico-w/demo-obc-ap", "pico-w/wifi-ap"]
demo-sd = ["cortex-m", "rp2040", "defmt", "dep:pico-w", "pico-w/demo-sd",]
pico-sky = ["cortex-m", "rp2040", "defmt", "dep:pico-w", "pico-w/demo-sky"]
pico-ground = ["cortex-m", "rp2040", "defmt", "dep:pico-w", "pico-w/demo-ground"]

esp32-humidity = ["esp32-c3", "defmt", "esp32c3/riscv", "esp32c3/run-temperature-and-humidity"]

# default = ["firmware"]

cortex-m = ["pico-w/cortex-m", "dep:cortex-m", "dep:cortex-m-rt", "dep:panic-probe"]
rp2040 = [
    "pico-w?/rp2040",
    "portable-atomic/critical-section",
    "portable-atomic/require-cas",
]

# wifi = ["esp-wifi"]

defmt = [
    "dep:defmt",
    "dep:defmt-rtt",
    "esp-println?/defmt-espflash",
    "esp-backtrace?/defmt",
    "esp32c3?/defmt",
    "pico-w?/defmt",
    # "heapless/defmt-impl",
    "panic-probe?/print-defmt",
]

log = [
    "dep:log",
    "esp32c3/log",
    "esp-println/log",
]

std = [
    "alloc",
    "critical-section/std",
    "portable-atomic/std",
]
alloc = []

# std = ["embassy-executor/arch-std", "once_cell/std", "critical-section/std"]
# riscv = [
    # "embassy-executor/arch-riscv32"
# ]

[dependencies]
esp32c3 = { version = "0.1", path = "esp32c3", default-features = false, optional = true }
pico-w = { version = "0.1", path = "pico-w", optional = true, default-features = false }

panic-probe = { workspace = true, optional = true }

cortex-m = { workspace = true, optional = true }
cortex-m-rt = { workspace = true, optional = true }

# ESP32C3
hal = { package = "esp-hal", version = "0.23", features = [
    # "async",
    "esp32c3",
], optional = true }
# debugging
esp-backtrace = { workspace = true, optional = true }
esp-println = { workspace = true, optional = true }

log = { workspace = true, optional = true }

defmt = { workspace = true, optional = true }
defmt-rtt = { workspace = true, optional = true }

# Allocator
# esp-alloc.workspace = true

# esp-wifi = { workspace = true, optional = true }
# Keep the same as in esp-wifi
# embedded-svc = { workspace = true, optional = true }

static_cell.workspace = true

heapless.workspace = true

fugit.workspace = true

# critical-section = { workspace = true }
critical-section = { version = "1.1" }
portable-atomic = { workspace = true }

# [patch.crates-io]
# icm42670 = { version = "0.1", path = "../icm42670" }

[build-dependencies]
dotenv = "0.15"