[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[features]
default = ["BMP388", "BNO055", "GNSS", "serde", "postcard", "status", "storage"]
all = ["std", "BMP388", "BNO055", "GNSS", "serde", "postcard", "status", "defmt-03", "bin", "storage"]
# default = []

std = ["serde?/std", "cli", "chrono?/std"]

cli = ["dep:clap"]

defmt-03 = [
    "dep:defmt",
    "bmp388?/defmt-03",
    "bno055?/defmt-03",
    "nmea?/defmt-03",
    "embedded-sdmmc?/defmt-log",
    "embedded-hal-async?/defmt-03",
    "heapless/defmt-03",
]
serde = ["dep:serde", "bno055?/serde", "bmp388?/serde", "nmea?/serde", "mint?/serde", "chrono?/serde", "num?/serde"]
postcard = ["dep:postcard", "dep:postcard-rpc", "serde"]

pressure-and-temperature = []
BMP388 = ["dep:bmp388"]

imu = []
BNO055 = ["dep:bno055"]

nmea = ["dep:nmea"]
GNSS = ["nmea"]

status = []

# the storage depends on Postcard and serde for serialization
storage = ["dep:embedded-sdmmc", "dep:embedded-hal-async", "postcard", "dep:crc", "dep:num"]

bin = ["std", "dep:serde_json", "dep:chrono", "dep:csv", "dep:mint", "dep:serde", "dep:clap"]

[dependencies]
serde = { workspace = true, default-features = false, optional = true }
postcard = { workspace = true, optional = true, features = ["experimental-derive"]}
postcard-rpc = { workspace = true, optional = true }

defmt = { workspace = true, optional = true }

# Sensors, peripherals and parsers
# Pressure and Temperature sensor
bmp388 = { workspace = true, optional = true, features = ["asynch", "config-builder"] }
# IMU
bno055 = { workspace = true, optional = true }
# Parsing NMEA 0183 senteneces from GNSS receiver
nmea = { workspace = true, optional = true, default-features = false, features = ["all-sentences"] }

# SD card storage
embedded-sdmmc = { workspace = true, optional = true }
embedded-hal-async = { workspace = true, optional = true }

serde_json = { version = "1", optional = true }
chrono = { version = "0.4", default-features = false, optional = true }

heapless = { workspace = true }
# CRC algorithms for SD card storage
crc = { version = "3.2", optional = true }
num = { workspace = true, default-features = false, optional = true }
# Math INteroperability Types used in bno055
mint = { version = "0.5", optional = true }

clap = { version = "4", features = ["cargo", "derive", "env"], optional = true }
csv = { version = "1.3", optional = true }

# [dev-dependencies]